In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [6]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [ ]:
# Create our features
X = pd.get_dummies(df)

# Create our target
y = df["loan_status"]

In [8]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,loan_status_low_risk,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.994958,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.070831,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,1.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,1.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,1.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [10]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [27]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
brf = BalancedRandomForestClassifier(n_estimators = 100, random_state=1)
brf.fit(X_train, y_train)
Counter(y_train)

Counter({'low_risk': 51369, 'high_risk': 243})

In [28]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix

y_pred = brf.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9995321910999357

In [29]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  104,     0],
       [   16, 17085]], dtype=int64)

In [30]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.87      1.00      1.00      0.93      1.00      1.00       104
   low_risk       1.00      1.00      1.00      1.00      1.00      1.00     17101

avg / total       1.00      1.00      1.00      1.00      1.00      1.00     17205

In [81]:
# List the features sorted in descending order by feature importance
model = brf.fit(X_test, y_test)
list(zip(X_test, model.feature_importances_))

[('loan_amnt', 0.007161982129550406),
 ('int_rate', 0.011441216503409082),
 ('installment', 0.005800215037406481),
 ('annual_inc', 0.006184297737199012),
 ('dti', 0.00876332828272269),
 ('delinq_2yrs', 0.00151080516639498),
 ('inq_last_6mths', 0.001745855955191143),
 ('open_acc', 0.008056184241752733),
 ('pub_rec', 0.0006664202392357734),
 ('revol_bal', 0.00544398325776646),
 ('total_acc', 0.00725369670203315),
 ('out_prncp', 0.005086436067824714),
 ('out_prncp_inv', 0.007341689297541642),
 ('total_pymnt', 0.03636941230019614),
 ('total_pymnt_inv', 0.035275862614245514),
 ('total_rec_prncp', 0.0377380247971137),
 ('total_rec_int', 0.04108209840424698),
 ('total_rec_late_fee', 0.0012724466959419165),
 ('recoveries', 0.0),
 ('collection_recovery_fee', 0.0),
 ('last_pymnt_amnt', 0.03328723694057065),
 ('collections_12_mths_ex_med', 0.0),
 ('policy_code', 0.0),
 ('acc_now_delinq', 0.0),
 ('tot_coll_amt', 0.0012333919705934122),
 ('tot_cur_bal', 0.0032623889811395435),
 ('open_acc_6m', 0.0012413200327246806),
 ('open_act_il', 0.002300198297838679),
 ('open_il_12m', 0.0025576556504148217),
 ('open_il_24m', 0.0038264048928855284),
 ('mths_since_rcnt_il', 0.008850968722565623),
 ('total_bal_il', 0.00813932752784549),
 ('il_util', 0.006874033233253832),
 ('open_rv_12m', 0.0010574209705591145),
 ('open_rv_24m', 0.0025031907909945673),
 ('max_bal_bc', 0.006266302079253723),
 ('all_util', 0.004628523333104466),
 ('total_rev_hi_lim', 0.0051837987751215805),
 ('inq_fi', 0.004719542290515803),
 ('total_cu_tl', 0.003625051508199973),
 ('inq_last_12m', 0.006570067848831065),
 ('acc_open_past_24mths', 0.004363983293062977),
 ('avg_cur_bal', 0.007074432978844716),
 ('bc_open_to_buy', 0.004723891737254199),
 ('bc_util', 0.005878048197408709),
 ('chargeoff_within_12_mths', 0.0002782931354359922),
 ('delinq_amnt', 0.0),
 ('mo_sin_old_il_acct', 0.004855046540993063),
 ('mo_sin_old_rev_tl_op', 0.00300753922657226),
 ('mo_sin_rcnt_rev_tl_op', 0.005720905610908218),
 ('mo_sin_rcnt_tl', 0.00884563659484165),
 ('mort_acc', 0.0022711933334062435),
 ('mths_since_recent_bc', 0.004733368622873658),
 ('mths_since_recent_inq', 0.009150304521537363),
 ('num_accts_ever_120_pd', 0.0013792341462229775),
 ('num_actv_bc_tl', 0.006112735733803791),
 ('num_actv_rev_tl', 0.002176342512821419),
 ('num_bc_sats', 0.0015284838823377697),
 ('num_bc_tl', 0.004592819310509061),
 ('num_il_tl', 0.0022918443522233337),
 ('num_op_rev_tl', 0.004602179060095186),
 ('num_rev_accts', 0.0041634702713018775),
 ('num_rev_tl_bal_gt_0', 0.004368358475287509),
 ('num_sats', 0.005779332390486982),
 ('num_tl_120dpd_2m', 0.0),
 ('num_tl_30dpd', 0.0),
 ('num_tl_90g_dpd_24m', 0.00042031580838127787),
 ('num_tl_op_past_12m', 0.002419922163027134),
 ('pct_tl_nvr_dlq', 0.0035100204286918797),
 ('percent_bc_gt_75', 0.0030374222716303928),
 ('pub_rec_bankruptcies', 0.0009296569784214741),
 ('tax_liens', 0.0),
 ('tot_hi_cred_lim', 0.008107665615989818),
 ('total_bal_ex_mort', 0.0036734088658608678),
 ('total_bc_limit', 0.004777687749729868),
 ('total_il_high_credit_limit', 0.00368230172500169),
 ('home_ownership_ANY', 0.0),
 ('home_ownership_MORTGAGE', 0.0007009515463329267),
 ('home_ownership_OWN', 0.0007024442693456792),
 ('home_ownership_RENT', 0.0012531368520003353),
 ('verification_status_Not Verified', 0.0005062817993166651),
 ('verification_status_Source Verified', 0.0),
 ('verification_status_Verified', 0.0003463439112945086),
 ('issue_d_Feb-2019', 0.004805940511061601),
 ('issue_d_Jan-2019', 0.010198324000966572),
 ('issue_d_Mar-2019', 0.00048691260739805843),
 ('loan_status_high_risk', 0.2644428661417786),
 ('loan_status_low_risk', 0.2474689633320968),
 ('pymnt_plan_n', 0.0),
 ('initial_list_status_f', 0.0012438745038839188),
 ('initial_list_status_w', 0.00029027463108809534),
 ('next_pymnt_d_Apr-2019', 0.0010398833641773809),
 ('next_pymnt_d_May-2019', 0.0021582081467977545),
 ('application_type_Individual', 0.0005578038233907597),
 ('application_type_Joint App', 0.0010211657479219883),
 ('hardship_flag_N', 0.0),
 ('debt_settlement_flag_N', 0.0)]

### Easy Ensemble AdaBoost Classifier

In [83]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)
eec.fit(X_train, y_train)

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [84]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, y_pred)

0.9995321910999357

In [85]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  104,     0],
       [   16, 17085]], dtype=int64)

In [86]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.87      1.00      1.00      0.93      1.00      1.00       104
   low_risk       1.00      1.00      1.00      1.00      1.00      1.00     17101

avg / total       1.00      1.00      1.00      1.00      1.00      1.00     17205